[accessibility]
ui_scale = 1.0000000074505806

[bar.default]
center = [ "active_window", "spacer_1", "clock", "date", "spacer_1", "weather" ]
concave_edge_corners = true
contact_shadow = true
end = [ "group:g1", "session" ]
margin_edge = 0
margin_ends = 0
position = "left"
radius_bottom_left = 12
radius_bottom_right = 12
radius_top_left = 0
radius_top_right = 12
scale = 1.1000000000000001
start = [ "launcher", "spacer_1", "workspaces", "media" ]
thickness = 35

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "tray", "network", "volume", "power_profile", "battery", "notifications" ]
    opacity = 1.0
    padding = 12.0

[calendar]
event_time_format = "%I:%M %P"

    [calendar.account.smblasik]
    name = "gmail"
    type = "google"

[control_center]
show_shortcut_labels = false

    [control_center.calendar]
    show_events_card = false

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 128.0
    box_width = 128.0
    cx = 608.0
    cy = 392.0
    output = "eDP-1"
    placement_height = 720.0
    placement_width = 1280.0
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false

[dock]
concave_edge_corners = false
enabled = true
icon_size = 40
inactive_opacity = 0.9499999787658453
item_spacing = 0
launcher_icon = "rocket"
launcher_position = "end"
main_axis_padding = 8
pinned = [ "thunar", "zen", "vesktop", "obsidian", "kitty", "fr.handbrake.ghb", "steam" ]
reserve_space = false
show_dots = true
smart_auto_hide = true

[hot_corners.top_left]
action = "window_switcher"

[location]
address = "Frisco, TX"

[lockscreen]
blur_intensity = 0.0

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@FALLBACK", "lockscreen-login-box@DP-1", "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@FALLBACK"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "FALLBACK"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@FALLBACK".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 640.0
    cy = 538.0
    output = "eDP-1"
    placement_height = 720.0
    placement_width = 1280.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true
temperature_day = 6900
temperature_night = 2400

[osd]
border = false
orientation = "vertical"
position_vertical = "center_right"

[shell]
app_icon_color = "primary"
button_borders = false
card_borders = false
clipboard_image_action_command = "satty -f -"
font_family = "Roboto"
input_borders = false
launch_apps_as_systemd_services = true
password_style = "random"
polkit_agent = true
popup_borders = false
settings_show_advanced = true
time_format = "{:%I:%M %P}"

    [shell.greeter_sync]
    auto_sync = true

    [shell.launcher]
    categories = false
    compact = true
    pinned = [
        "vesktop",
        "proton.vpn.app.gtk",
        "fr.handbrake.ghb",
        "mpv",
        "steam",
        "obsidian",
        "btrfs-assistant",
        "kitty",
        "org.kde.dolphin"
    ]

        [shell.launcher.providers.emoji]
        global = true

        [shell.launcher.providers.session]
        global = true

        [shell.launcher.providers.wallpaper]
        global = true

    [shell.panel]
    clipboard_position = "top_center"
    control_center_position = "center"
    launcher_position = "bottom_center"
    open_near_click_control_center = true
    session_placement = "floating"
    session_position = "center"
    wallpaper_placement = "floating"
    wallpaper_position = "center"

    [shell.screenshot]
    copy_to_clipboard = false
    pipe_command = "satty -f -"
    pipe_to_command = true
    save_to_file = false

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 3.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[system.monitor]
gpu_poll_seconds = 2

[theme]
builtin = "Noctalia"
community_palette = "Tomorrow"
mode = "dark"
pure_black_dark = true
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "cava", "foot", "gtk3", "gtk4", "hyprland", "kcolorscheme", "kitty", "qt", "starship" ]
    community_ids = [ "papirus-icons" ]

[wallpaper.default]
path = "/home/scott/Pictures/IMG_2644.JPG"

[wallpaper.last]
path = "/home/scott/Pictures/IMG_2644.JPG"

[wallpaper.monitors.eDP-1]
path = "/home/scott/Pictures/IMG_2644.JPG"

[[wallpaper.favorite]]
palette_source = "wallpaper"
path = "/home/scott/Pictures/creation-of-adam.jpeg"
theme_mode = "dark"
wallpaper_scheme = "m3-tonal-spot"

[[wallpaper.favorite]]
path = "/home/scott/Pictures/IMG_2644.JPG"
theme_mode = "auto"

[[wallpaper.favorite]]
palette_source = "wallpaper"
path = "/home/scott/Pictures/IMG_0001.JPG"
theme_mode = "dark"
wallpaper_scheme = "m3-content"

[weather]
effects = false
unit = "imperial"

[widget.active_window]
display = "icon_only"

[widget.battery]
color = "secondary"
hide_when_full = true
hide_when_plugged = true
show_label = false

[widget.bluetooth]
color = "secondary"

[widget.clock]
anchor = true
color = "secondary"
font_weight = 700
format = "{:%I:%M :%p}"

[widget.date]
color = "secondary"
enabled = false
format = "{:%p}"
scale = 0.80000000000000004

[widget.launcher]
color = "secondary"
glyph = "grid-dots"

[widget.media]
hide_when_no_media = true
title_scroll = "on_hover"

[widget.network]
color = "secondary"
show_label = false

[widget.notifications]
color = "secondary"
hide_when_no_unread = true

[widget.power_profile]
color = "secondary"

[widget.session]
color = "error"

[widget.spacer_1]
enabled = false
type = "spacer"

[widget.sysmon_2]
glyph = "gpu-usage"
show_value = false
stat = "gpu_temp"
type = "sysmon"

[widget.sysmon_3]
glyph = "cpu-2"
stat = "ram_used"
type = "sysmon"

[widget.temp]
show_value = false

[widget.tray]
capsule = false
capsule_fill = "on_secondary"

[widget.volume]
color = "secondary"
show_label = false

[widget.weather]
color = "secondary"
scale = 0.80000000000000004
show_condition = false

[widget.workspaces]
active_pill_size = 2.5
capsule = true
capsule_fill = "surface_variant"
capsule_padding = 8
capsule_radius = "auto"
inactive_pill_size = 1.0
pill_scale = 0.80000000000000004
show_labels = false
